spring:
  application:
    name: ecard

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

ecard:
  frontend:
    url: https://e-greeting-card.vercel.app/

logging:
  level:
    org.hibernate.SQL: DEBUG

  # Uncomment if you want Spring Framework debugging logs
  # org.springframework: DEBUG